name: PR validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - datafix/**
    paths:
      - LawVu*/**

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: echo "running tests ..."
      
