name: PR validation

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - notes/*

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: echo "running tests ..."
      
