name: PR validation

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - notes/*

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      # this will always fail, that's on purpose. it should block the PR
      - name: run tests
        run: dotnet tests
      
